### ISSUE TITLE
add support for ULID to swagger:strfmt

### ISSUE THREAD

**Issue by elipavlov** [go-openapi/strfmt#77]
## Enhancement description

It's great that we have feature like string format for the UUID strings like here:
https://goswagger.io/use/spec/strfmt.html

Recently i've learnt about ULID identity provider: 
https://github.com/ulid/spec

My proposal is to add the same helper for the ULID format.

## Swagger spec examples

1) 
```yaml
---
definitions:
  user:
    properties:
      id:
        type: string
        format: ulid
```

2) 
```yaml
---
definitions:
  ULIDType:
    type: string
    format: ulid
  User:
    properties:
      id:
        $ref: '#/definitions/ULIDType'
```

P.S.

Originally created here: [go-swagger#2467](https://github.com/go-swagger/go-swagger/issues/2467)
